-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 23:09:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auth-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth-db` DEFAULT CHARACTER SET utf8mb4 ;
USE `auth-db` ;

SET CHARSET utf8mb4;

-- -----------------------------------------------------
-- Table `auth-db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth-db`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ユーザID',
  `email` VARCHAR(128) NOT NULL COMMENT 'メールアドレス',
  `password` VARCHAR(128) NOT NULL COMMENT 'パスワード',
  PRIMARY KEY (`user_id`),
  UNIQUE (`email`)
)
ENGINE = InnoDB
COMMENT = 'ユーザ';


-- -----------------------------------------------------
-- Table `auth-db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth-db`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ProductID',
  `product_name` VARCHAR(64) NOT NULL COMMENT 'Product名前',
  `product_number` VARCHAR(128) NOT NULL COMMENT 'Product個別番号',
  PRIMARY KEY (`product_id`),
  UNIQUE (`product_number`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth-db`.`UserProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth-db`.`UserProduct` (
  `user_product_id` INT NOT NULL AUTO_INCREMENT COMMENT 'User所持製品id',
  `user_id` INT NOT NULL COMMENT 'ユーザID',
  `product_id` INT NOT NULL COMMENT 'ProductID',
  PRIMARY KEY (`user_product_id`),
  UNIQUE (`user_id`, `product_id`),
  INDEX `fk_User_Product_user_id_idx` (`user_id` ASC),
  INDEX `fk_user_Product_product_id_idx` (`product_id` ASC),
  CONSTRAINT `fk_User_Product_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth-db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_Product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `auth-db`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ユーザ所持製品';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
